### ISSUE TITLE
TypeError: tables.filter is not a function

### ISSUE THREAD

**Issue by briviere** [benoror/ember-postgrest-dynamic-ui#2]
Hello 

I'm getting the following error's.  I not exactly sure why this is happening?

ember.debug.js:28535 Error while processing route: index tables.filter is not a function TypeError: tables.filter is not a function
    at http://localhost:4200/assets/vendor.js:127670:23
    at tryCatch (http://localhost:4200/assets/vendor.js:63955:14)
    at invokeCallback (http://localhost:4200/assets/vendor.js:63970:15)
    at publish (http://localhost:4200/assets/vendor.js:63938:9)
    at http://localhost:4200/assets/vendor.js:42203:7
    at invoke (http://localhost:4200/assets/vendor.js:10482:16)
    at Queue.flush (http://localhost:4200/assets/vendor.js:10546:11)
    at DeferredActionQueues.flush (http://localhost:4200/assets/vendor.js:10354:17)
    at Backburner.end (http://localhost:4200/assets/vendor.js:10709:25)
    at http://localhost:4200/assets/vendor.js:11275:18logError @ ember.debug.js:28535
ember.debug.js:32096 TypeError: tables.filter is not a function
    at postgrest-route.js:12
    at tryCatch (ember.debug.js:53806)
    at invokeCallback (ember.debug.js:53821)
    at publish (ember.debug.js:53789)
    at ember.debug.js:32054
    at invoke (ember.debug.js:333)
    at Queue.flush (ember.debug.js:397)
    at DeferredActionQueues.flush (ember.debug.js:205)
    at Backburner.end (ember.debug.js:560)
    at ember.debug.js:1126

**Comment by benoror** [comment]
Sorry for late response, did you found the issue? Are you running PostgREST in the background?

**Comment by briviere** [comment]
Hello

Yes I do have postgrest running on http://localhost:3000

thanks

Brian

**Comment by benoror** [comment]
Did you created some tables? Also did you created the `meta_fields_templates` table? I can send you a SQL script if you'd like

**Comment by briviere** [comment]
Hello Ben

NO i did not create a meta_field_templates table.  If you can send me the
script that would be great.

thanks

Brian

**Comment by benoror** [comment]
I added the sql dump: https://github.com/benoror/ember-postgrest-dynamic-ui/blob/master/demo.sql

Feel free to reach me if you have other issues.

Cheers!
